language: cpp
sudo: false  # docker VM
git:
  depth: 99999
cache:
  directories:
  - libdeps
matrix:
  include:
  - os: windows
    env: MATRIX_EVAL="choco install -y msys2 && env PATH=\"/c/tools/msys64/usr/bin:$PATH\" bash msys2_build.sh"
    filter_secrets: false # note: means we can't deploy until "secrets" bug related to choco is fixed!
before_install:
  - eval "${MATRIX_EVAL}"
script:  pwd && ./bootstrap.sh && ./autogen.sh --prefix=$PWD/install && make && make check && make install && bash .travis-ghpages.sh || cat config.log
after_script:
- 
# - make distcheck # will not work without re-bootstrapping, wasteful
notifications:
  email:
    recipients:
      - radarsat1@gmail.com
    on_success: never
    on_failure: change
