language: cpp
sudo: false  # docker VM
cache:
  directories:
  - libdeps
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-8
          - libusb-dev
          - freeglut3-dev
          - autoconf-archive
          - libsamplerate0-dev
          - libasound2-dev
          - libusb-1.0-0-dev
          - unzip
          - libasound2-dev
          - libxcursor-dev
          - libxrandr-dev
          - libxinerama-dev
    env: HOST="" MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    compiler: gcc
  - os: osx
    osx_image: xcode10
    env: HOST="" MATRIX_EVAL="brew install freeglut autoconf-archive"
    compiler: clang
before_install:
  - eval "${MATRIX_EVAL}"
script:  ./bootstrap.sh && ls libdeps && ls libdeps/chai3d-3.2.0/src && (./autogen.sh || cat config.log) && make
after_script:
- make check
- make distcheck
- make install
notifications:
  email:
    recipients:
      - radarsat1@gmail.com
    on_success: never
    on_failure: change
